development:
  STATUSES: 
    [
      [0, 'Normal'], 
      [1, 'Paralysis'], 
      [2, 'Poison'], 
      [3, 'Sleep'], 
      [4, 'Frozen'], 
      [5, 'Burn']
    ]
  TYPES: 
    [
      [0, 'Normal'],
      [1, 'Fire'],
      [2, 'Water'],
      [3, 'Grass'],
      [4, 'Electric'],
      [5, 'Ice'],
      [6, 'Fighting'],
      [7, 'Poison'],
      [8, 'Ground'], 
      [9, 'Flying'], 
      [10, 'Psychic'], 
      [11, 'Bug'], 
      [12, 'Rock'], 
      [13, 'Ghost'], 
      [14, 'Dragon']
  ]
  GROWTH:
    {
      'Normal':2,
      'Fire':2,
      'Water':2,
      'Grass':2,
      'Electric':2,
      'Ice':1.5,
      'Fighting':1.5,
      'Poison':1.5,
      'Ground':1.5,
      'Flying':1.5,
      'Psychic':1.5,
      'Bug':1,
      'Rock':1,
      'Ghost':1,
      'Dragon':1
    }

production:
  <<: development